repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# Just ruff - handles 90% of what you need, super fast
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: local
    hooks:
    -   id: import-test
        name: import-test
        entry: python -c "import keras_geometric; print('✅ All imports working')"
        language: system
        pass_filenames: false
        files: ^src/keras_geometric
